spring:
  application:
    name: yt-clone
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#TODO set file size limits, and set threshold so spring will copy file instead of handling it in memory
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE